### ISSUE TITLE
Beta masaheft demo broken

### ISSUE THREAD

**Issue by mromanello** [distributed-text-services/implementation-demos#2]
(I've ran the notebooks with https://mybinder.org/v2/gh/distributed-text-services/implementation-demos/master)

Beta masaheft's DTS endpoint seems to respond with a `444` http status code:

```
URI = "https://betamasaheft.eu/api/dts"
entry_request = requests.get(URI)
entry_request.status_code
>>> 444
```

If I try with `cURL` on curl https://betamasaheft.eu/api/dts I get as a response 

```
curl https://betamasaheft.eu/api/dts
>>> https://www.google.com/
```

is it perhaps something to do with bot configuration?

**Comment by PietroLiuzzo** [comment]
This is a configuration of our nginx proxy which responds with 444 to any request without a UserAgent.

**Comment by mromanello** [comment]
thanks @PietroLiuzzo !

in fact this does trick:

```python
headers = {
    'User-Agent': 'My User Agent 1.0'
}
entry_request = requests.get(URI, headers=headers)
```

the only slight inconvenience is that one needs to pass the `headers` parameter for every `get()` call -- but it's doable, just a matter of knowing.

As soon as I find a moment to do this, I'll open a PR to address this issue with an updated version of the notebook where this behaviour of BM's endpoint is briefly explained.

**Comment by PonteIneptique** [comment]
Matteo, could I ask you to take the time to do the same on MyCapytain ? 
I am not sure I am sending UserAgent :)

Le 12/09/2019 à 14:09, Matteo Romanello a écrit :

**Comment by PietroLiuzzo** [comment]
thanks, this setting has proved very succesfull for us in keeping malicious bots out, so, I would very much like to keep it in place.

**Comment by mromanello** [comment]
@PonteIneptique can you open an issue for that on MyCapytain :) ?

**Comment by PonteIneptique** [comment]
That's what I was asking you :'(
Tsss ;)
